"""Server-side PDF export for Pro reports.

Uses ReportLab (pure Python, no system Chromium) to render the narrative
plus a clean table of the key computed statistics. Charts are omitted from
the PDF in this pass — the narrative + stats table carry the substance.
"""
from __future__ import annotations

import io
from datetime import datetime
from typing import Any

from reportlab.lib import colors
from reportlab.lib.enums import TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

BORDER = colors.HexColor("#232A33")
MUTED = colors.HexColor("#8A94A3")
ACCENT = colors.HexColor("#00D4FF")
TEXT = colors.HexColor("#0B0E11")


def _styles():
    base = getSampleStyleSheet()
    title = ParagraphStyle(
        "DSTitle",
        parent=base["Title"],
        fontName="Helvetica-Bold",
        fontSize=20,
        leading=24,
        textColor=TEXT,
        alignment=TA_LEFT,
        spaceAfter=2 * mm,
    )
    meta = ParagraphStyle(
        "DSMeta",
        parent=base["Normal"],
        fontName="Helvetica",
        fontSize=9,
        leading=12,
        textColor=MUTED,
        spaceAfter=6 * mm,
    )
    h2 = ParagraphStyle(
        "DSH2",
        parent=base["Heading2"],
        fontName="Helvetica-Bold",
        fontSize=13,
        leading=16,
        textColor=TEXT,
        spaceBefore=6 * mm,
        spaceAfter=3 * mm,
    )
    body = ParagraphStyle(
        "DSBody",
        parent=base["BodyText"],
        fontName="Helvetica",
        fontSize=10.5,
        leading=16,
        textColor=TEXT,
    )
    return title, meta, h2, body


def _kv_table(rows: list[list[str]]) -> Table:
    ncols = len(rows[0]) if rows else 2
    widths = [60 * mm] + [(180 - 60 * mm) / (ncols - 1) * mm for _ in range(ncols - 1)]
    table = Table(rows, colWidths=widths)
    table.setStyle(
        TableStyle(
            [
                ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
                ("FONTSIZE", (0, 0), (-1, -1), 9),
                ("TEXTCOLOR", (0, 0), (0, -1), MUTED),
                ("TEXTCOLOR", (1, 0), (1, -1), TEXT),
                ("BACKGROUND", (0, 0), (-1, -1), colors.white),
                ("LINEBELOW", (0, 0), (-1, -2), 0.4, BORDER),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                ("TOPPADDING", (0, 0), (-1, -1), 6),
            ]
        )
    )
    return table


def build_pdf(filename: str, summary: dict[str, Any], narrative: str) -> bytes:
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=A4,
        rightMargin=20 * mm,
        leftMargin=20 * mm,
        topMargin=18 * mm,
        bottomMargin=18 * mm,
        title=f"DataScope — {filename}",
        author="DataScope",
    )

    title, meta, h2, body = _styles()
    story = [
        Paragraph(f"DataScope analysis — {filename}", title),
        Paragraph(
            f"Generated {datetime.utcnow().strftime('%B %d, %Y')} · "
            f"{summary['shape']['rows']} rows × {summary['shape']['columns']} columns",
            meta,
        ),
        Paragraph("Narrative", h2),
        Paragraph(narrative.replace("\n", "<br/>"), body),
    ]

    # Missing values
    missing = [(k, v) for k, v in summary.get("missing_pct", {}).items() if v > 0]
    if missing:
        story.append(Paragraph("Missing values", h2))
        story.append(
            _kv_table(
                [["Column", "Percent missing"]]
                + [[k, f"{v:.1f}%"] for k, v in missing]
            )
        )

    # Outliers
    outliers = {
        k: v
        for k, v in summary.get("outliers", {}).items()
        if v.get("count")
    }
    if outliers:
        story.append(Paragraph("Outliers (IQR)", h2))
        story.append(
            _kv_table(
                [["Column", "Count", "Share of rows"]]
                + [
                    [k, str(v["count"]), f"{v['share'] * 100:.1f}%"]
                    for k, v in outliers.items()
                ]
            )
        )

    # Strong correlations
    pairs = []
    corr = summary.get("correlations", {})
    for a, targets in corr.items():
        for b, r in targets.items():
            if a >= b or r is None or abs(r) <= 0.7:
                continue
            pairs.append([a, b, f"{r:.3f}"])
    if pairs:
        story.append(Paragraph("Strong correlations", h2))
        story.append(_kv_table([["Column A", "Column B", "r"]] + pairs))

    story.append(Spacer(1, 6 * mm))
    story.append(
        Paragraph(
            "Generated by DataScope. Upgrade to Pro for unlimited reports.",
            ParagraphStyle(
                "footer",
                parent=meta,
                fontName="Helvetica",
                fontSize=8,
                leading=10,
                textColor=MUTED,
            ),
        )
    )

    doc.build(story)
    return buf.getvalue()
