import Link from "next/link";
import { notFound } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { getReportWithUpload } from "@/lib/queries";
import { ReportOverview } from "@/components/report/report-overview";
import { ReportFindings } from "@/components/report/report-findings";
import { SampleNotice } from "@/components/report/sample-notice";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";

export const dynamic = "force-dynamic";

export default async function ReportOverviewPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = await params;
  const supabase = await createClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) notFound();

  const report = await getReportWithUpload(supabase, id);
  if (!report) notFound();

  const summary = report.summary_json;
  const findings = summary.findings ?? [];
  const topFindings = [...findings]
    .sort(
      (a, b) =>
        ({ high: 0, medium: 1, low: 2, info: 3 }[a.severity] ?? 9) -
        ({ high: 0, medium: 1, low: 2, info: 3 }[b.severity] ?? 9)
    )
    .slice(0, 5);

  return (
    <div className="space-y-8">
      <ReportOverview summary={summary} />

      <SampleNotice sample={report.sample_info_json} />

      {/* Narrative */}
      <Card>
        <CardHeader>
          <CardTitle>What the data says</CardTitle>
          <CardDescription>Generated by the DataScope analysis agent</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="space-y-4 text-[15px] leading-7">
            {report.narrative.split("\n").filter(Boolean).map((para, i) => (
              <p key={i}>{para}</p>
            ))}
          </div>
        </CardContent>
      </Card>

      {/* Top findings */}
      {findings.length > 0 && (
        <Card>
          <CardHeader>
            <CardTitle>Top findings</CardTitle>
            <CardDescription>
              {findings.length} evidence-backed issues worth knowing about
            </CardDescription>
          </CardHeader>
          <CardContent>
            <ReportFindings findings={topFindings} />
            {findings.length > 5 && (
              <div className="mt-4">
                <Button asChild variant="ghost" size="sm">
                  <Link href={`/dashboard/reports/${id}/findings`}>
                    View all {findings.length} findings
                  </Link>
                </Button>
              </div>
            )}
          </CardContent>
        </Card>
      )}

      {/* Dataset overview */}
      <Card>
        <CardHeader>
          <CardTitle>Dataset overview</CardTitle>
          <CardDescription>
            Column types detected by pandas
          </CardDescription>
        </CardHeader>
        <CardContent className="flex flex-wrap gap-2">
          {Object.entries(summary.dtypes).map(([col, dtype]) => {
            const kind = summary.column_classification?.[col]?.kind;
            const label =
              kind && kind !== "categorical" && kind !== "numeric"
                ? `${dtype} · ${kind.replace("_", " ")}`
                : dtype;
            return (
              <div
                key={col}
                className="flex items-center gap-2 rounded-md border border-border bg-elevated px-3 py-1.5"
              >
                <span className="text-sm text-foreground">{col}</span>
                <span className="text-xs text-muted">{label}</span>
              </div>
            );
          })}
        </CardContent>
      </Card>

      {/* Column glossary */}
      {report.column_glossary && Object.keys(report.column_glossary).length > 0 && (
        <Card>
          <CardHeader>
            <CardTitle>Column glossary</CardTitle>
            <CardDescription>How each column was interpreted by the analysis agent</CardDescription>
          </CardHeader>
          <CardContent>
            <dl className="grid gap-2 sm:grid-cols-2">
              {Object.entries(report.column_glossary).map(([col, def]) => (
                <div key={col} className="rounded-md border border-border bg-elevated px-3 py-2">
                  <dt className="text-sm font-medium">{col}</dt>
                  <dd className="mt-0.5 text-xs text-muted">{def}</dd>
                </div>
              ))}
            </dl>
          </CardContent>
        </Card>
      )}
    </div>
  );
}
