import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, Download } from "lucide-react";
import { createClient } from "@/lib/supabase/server";
import { ReportCharts } from "@/components/report/report-charts";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import type { Plan, Profile, Report, Upload } from "@/lib/types";

export const dynamic = "force-dynamic";

interface ReportWithUpload extends Report {
  uploads: Pick<Upload, "id" | "filename" | "created_at">;
}

function formatDate(iso: string): string {
  return new Date(iso).toLocaleDateString(undefined, {
    year: "numeric",
    month: "short",
    day: "numeric",
  });
}

export default async function ReportPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = await params;
  const supabase = await createClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) notFound();

  const { data: report } = await supabase
    .from("reports")
    .select("id, upload_id, summary_json, narrative, created_at, uploads(id, filename, created_at)")
    .eq("id", id)
    .single<ReportWithUpload>();

  if (!report) notFound();

  const { data: profile } = await supabase
    .from("profiles")
    .select("plan")
    .single<Pick<Profile, "plan">>();

  const isPro = profile?.plan === "pro";
  const summary = report.summary_json;

  return (
    <div className="space-y-8">
      <div>
        <Link
          href="/dashboard"
          className="inline-flex items-center gap-1 text-sm text-muted hover:text-foreground"
        >
          <ArrowLeft className="h-4 w-4" /> Dashboard
        </Link>
        <div className="mt-4 flex flex-col justify-between gap-4 md:flex-row md:items-end">
          <div>
            <h1 className="text-3xl font-medium">{report.uploads.filename}</h1>
            <p className="mt-1 text-sm text-muted">
              Analyzed {formatDate(report.created_at)} ·{" "}
              {summary.shape.rows.toLocaleString()} rows ×{" "}
              {summary.shape.columns} columns
            </p>
          </div>
          {isPro && (
            <form
              action={`/api/reports/${report.id}/pdf`}
              method="get"
              target="_blank"
            >
              <Button type="submit" variant="outline" size="sm">
                <Download className="h-4 w-4" /> Download PDF
              </Button>
            </form>
          )}
        </div>
      </div>

      {/* Narrative */}
      <Card>
        <CardHeader>
          <CardTitle>What the data says</CardTitle>
          <CardDescription>Generated by the DataScope analysis agent</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="space-y-4 text-[15px] leading-7">
            {report.narrative.split("\n").filter(Boolean).map((para, i) => (
              <p key={i}>{para}</p>
            ))}
          </div>
        </CardContent>
      </Card>

      {/* Overview */}
      <Card>
        <CardHeader>
          <CardTitle>Dataset overview</CardTitle>
          <CardDescription>
            Column types detected by pandas
          </CardDescription>
        </CardHeader>
        <CardContent className="flex flex-wrap gap-2">
          {Object.entries(summary.dtypes).map(([col, dtype]) => (
            <div
              key={col}
              className="flex items-center gap-2 rounded-md border border-[#232a33] bg-[#1b2230] px-3 py-1.5"
            >
              <span className="text-sm text-foreground">{col}</span>
              <span className="text-xs text-muted">{dtype}</span>
            </div>
          ))}
        </CardContent>
      </Card>

      {/* Charts — only the ones relevant to what was flagged */}
      <ReportCharts summary={summary} />
    </div>
  );
}
